version: '2.1'

services:
  profileapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  marketing:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  emailapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  feedbackapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
